---
# defaults file for ansible-zabbix-docker
zabbix_version: "latest"
zabbix_data_path: "/usr/infra/zabbix"
zabbix_name: "Zabbix Server"
zabbix_timezone: "Etc/GMT" 
zabbix_database: zabbix
zabbix_db_user: zabbix
zabbix_db_password: zabbix
mysql_root_password: root_pw
